apiVersion: v1
kind: ConfigMap
metadata:
  name: digital-dice-config
data:
  PORT_CONTROLLER: "443" # Port for the controller
  PORT2_CONTROLLER: "80" # Alternative port for the controller
  PORT_DH: "8063" # Port for the datahandler
  PORT_EH: "8064" # Port for the eventhandler
  PORT_VIRTUALIZER: "8065" # Port for the virtualizer
  PORT_UI: "8066" # Port for the UI
  SUITCASE_URI: "192.168.1.17" # IP address of the device
  DH: "https://digital-dice-dh-entrypoint" # Datahandler entrypoint
  EH: "https://digital-dice-eh-entrypoint" # Eventhandler entrypoint
  DB_NAME: "dd-db" # Database name
  DB_USER: "dd_admin" # Database user
  DB_PASS: "123456admin" # Database password
  DB_URI: "mongodb://192.168.1.2/"
  TD_O_URL: "https://localhost:30001" # URL for the Thing Description
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: digital-dice-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digital-dice-controller
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: /metrics
        prometheus.io/port: '443'
      labels:
        app: digital-dice-controller
    spec:
      containers:
      - name: digital-dice-controller
        image: manelme/digital-dice-controller:0.1.0
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
        envFrom:
          - configMapRef:
              name: digital-dice-config
        volumeMounts:
          - name: tls-digital-dice
            mountPath: "/app/certs"
            readOnly: true
          - name: td-config
            mountPath: "/app/td"
            readOnly: true
      volumes:
        - name: tls-digital-dice
          secret:
            secretName: tls-digital-dice
        - name: td-config
          configMap:
            name: td-config
---
apiVersion: v1
kind: Service
metadata:
  name: digital-dice-controller-entrypoint
spec:
  type: NodePort
  selector:
    app: digital-dice-controller
  ports:
  - port: 443
    targetPort: 443
    nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: digital-dice-dh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digital-dice-dh
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: /metrics
        prometheus.io/port: '443'
      labels:
        app: digital-dice-dh
    spec:
      containers:
      - name: digital-dice-dh
        image: manelme/digital-dice-dh:0.1.0
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
        envFrom:
          - configMapRef:
              name: digital-dice-config
        volumeMounts:
          - name: tls-digital-dice
            mountPath: "/app/certs"
            readOnly: true
          - name: td-config
            mountPath: "/app/td"
            readOnly: true
      volumes:
        - name: tls-digital-dice
          secret:
            secretName: tls-digital-dice
        - name: td-config
          configMap:
            name: td-config
---
apiVersion: v1
kind: Service
metadata:
  name: digital-dice-dh-entrypoint
spec:
  selector:
    app: digital-dice-dh
  ports:
  - protocol: TCP
    port: 8063
    targetPort: 8063
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: digital-dice-controller
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: digital-dice-controller
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: digital-dice-dh
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: digital-dice-dh
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50