apiVersion: v1
kind: ConfigMap
metadata:
  name: digitaldice-config
data:
  PORT_CONTROLLER: "443"
  PORT2_CONTROLLER: "80"
  PORT_DH: "8063"
  PORT_EH: "8064"
  DEVICE_URI: "192.168.1.38"
  DH: "https://dd-suitcase-dh-entrypoint"
  EH: "https://dd-suitcase-eh-entrypoint"
  DB_NAME: "dd-db"
  DB_USER: "dd_admin"
  DB_PASS: "123456admin"
  DB_URI: "mongodb://mongo-0.mongo-headless.default:27017,mongo-1.mongo-headless.default:27017,mongo-2.mongo-headless.default:27017/"
  
