apiVersion: v1
kind: ConfigMap
metadata:
  name: digitaldice-config
data:
  PORT_CONTROLLER: "443"
  PORT2_CONTROLLER: "80"
  PORT_DH: "8063"
  PORT_EH: "8064"
  DEVICE_URI: "192.168.1.38"
  DH: "https://dd-suitcase-dh-entrypoint"
  EH: "https://dd-suitcase-eh-entrypoint"
  DB_NAME: "dd-db"
  DB_USER: "dd_admin"
  DB_PASS: "123456admin"
  DB_URI: "mongodb://mongo-0.mongo-headless.default:27017,mongo-1.mongo-headless.default:27017,mongo-2.mongo-headless.default:27017/"
  TD_O: "{
    \"@context\": \"https://www.w3.org/2022/wot/td/v1.1\",
    \"id\": \"urn:uuid:0804d572-cce8-422a-bb7c-4412fcd56f06\",
    \"title\": \"MyLampThing\",
    \"securityDefinitions\": {
        \"basic_sc\": {\"scheme\": \"basic\", \"in\": \"header\"}
    },
    \"security\": \"basic_sc\",
    \"properties\": {
        \"status\": {
            \"type\": \"string\",
            \"forms\": [{\"href\": \"https://mylamp.example.com/status\"}]
        }
    },
    \"actions\": {
        \"toggle\": {
            \"forms\": [{\"href\": \"https://mylamp.example.com/toggle\"}]
        }
    },
    \"events\": {
        \"overheating\": {
            \"data\": {\"type\": \"string\"},
            \"forms\": [{
                \"href\": \"https://mylamp.example.com/oh\",
                \"subprotocol\": \"longpoll\"
            }]
        }
    }
  }"
  TD_O_URL: "https://example.com"
  

