version: '3.8'

services:
  controller:
    build:
      context: ./controller
      dockerfile: Dockerfile
    container_name: controller
    volumes:
      - ./certs:/usr/src/app/certs
    ports:
      - "1480:80"
      - "14443:443"
    environment:
      - PORT_CONTROLLER=443
      - PORT2_CONTROLLER=80
      - PORT_DH=8063
      - PORT_EH=8064
      - DEVICE_URI=192.168.1.38
      - DH=https://dh
      - EH=https://eh
      - DB_NAME=dd-db
      - DB_USER=dd_admin
      - DB_PASS=123456admin
      - DB_PORT=27071
      - DB_HOST=192.168.1.2
      - DB_URI=mongodb://192.168.1.2:27071/
    depends_on:
      - dh
      - eh

  dh:
    build:
      context: ./datahandler
      dockerfile: Dockerfile
    container_name: dh
    volumes:
      - ./certs:/usr/src/app/certs
    ports:
      - "8063:443"
    environment:
      - PORT_CONTROLLER=443
      - PORT2_CONTROLLER=80
      - PORT_DH=8063
      - PORT_EH=8064
      - DEVICE_URI=192.168.1.38
      - DH=https://dh
      - EH=https://eh
      - DB_NAME=dd-db
      - DB_USER=dd_admin
      - DB_PASS=123456admin
      - DB_PORT=27071
      - DB_HOST=192.168.1.2
      - DB_URI=mongodb://192.168.1.2:27071/

  eh:
    build:
      context: ./eventhandler
      dockerfile: Dockerfile
    container_name: eh
    volumes:
      - ./certs:/usr/src/app/certs
    ports:
      - "8064:443"
    environment:
      - PORT_CONTROLLER=443
      - PORT2_CONTROLLER=80
      - PORT_DH=8063
      - PORT_EH=8064
      - DEVICE_URI=192.168.1.38
      - DH=https://dh
      - EH=https://eh
      - DB_NAME=dd-db
      - DB_USER=dd_admin
      - DB_PASS=123456admin
      - DB_PORT=27071
      - DB_HOST=192.168.1.2
      - DB_URI=mongodb://192.168.1.2:27071/